---
name: warnings-compat
version: 0.04
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: warnings.pm emulation for pre-5.6 Perls
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  warnings::compat:
    file: lib/warnings/compat.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
