--- #YAML:1.0
name:                warnings-compat
version:             0.01
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
